name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: unit- test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup gcloud for Cloud Build
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.TEST_PROJECT_ID }}
          service_account_key: ${{ secrets.TEST_SA_CREDENTIALS }}
          export_default_credentials: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        name: format check
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        name: clippy
        with:
          command: clippy
      - uses: actions-rs/cargo@v1
        name: test
        with:
          command: test
          args: --release --all-features
        env:
          TEST_USER_CREDENTIALS: ${{ secrets.TEST_USER_CREDENTIALS }}